version: '3.9'
services:
    remvze:
        image: ghcr.io/remvze/moodist
        logging:
            options:
                max-size: 1g
        restart: always
        ports:
            - '8080:8080'